#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Sunday 30 November 2025  22:53:54
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.3"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 845
y_pos = 671
width = 683
height = 200

[DIGITAL_KLOCK]
backgroundColour = "Black"
foregroundColour = "Green"
