#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Thursday 13 November 2025  20:37:15
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.1"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 100
y_pos = 503
width = 683
height = 200

