#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Monday 01 December 2025  22:47:30
#
#   true and false are lower case 
#
[INFO]
myVERSION = "2025.4"
myNAME = "pyKlock"

[APPLICATION]
x_pos = 84
y_pos = 43
width = 683
height = 200
backgroundColour = "Black"
foregroundColour = "Green"
transparent = true
transparency = 64

[DIGITAL_KLOCK]
backgroundColour = "Black"
foregroundColour = "Green"
